name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3.1
        with:
          version: v3.8.0
      - run: |
          helm dependency update charts/galactus
          helm lint charts/galactus
      - uses: stackrox/kube-linter-action@v1
        continue-on-error: true
        with:
          directory: charts/galactus

  kubeval:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3.1
        with:
          version: v3.8.0
      - run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          cp kubeval /usr/local/bin
      - run: |
          helm dependency update charts/galactus
          helm template charts/galactus | kubeval

  ct-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v3.1
        with:
          version: v3.8.0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: helm/chart-testing-action@v2.2.0
      - id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - run: ct lint --config ct.yaml

  ct-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v3.1
        with:
          version: v3.8.0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: helm/chart-testing-action@v2.2.0
      - id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - run: ct lint --config ct.yaml
      - uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'
      - run: ct install --config ct.yaml
